//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shikhragimov.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public int Id_s { get; set; }
        public int IdDol { get; set; }
        public string FIO { get; set; }
        public string Email { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Number_phone { get; set; }
        public string Ser_num_pas { get; set; }
        public System.DateTime Birthday { get; set; }
        public System.DateTime Pos_v { get; set; }
        public Nullable<int> IdType { get; set; }
        public int IdGender { get; set; }
    
        public virtual Dol Dol { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Type Type { get; set; }
    }
}
